### ISSUE TITLE
cd Vk-Tokenner

### ISSUE THREAD

**Issue by Inters3llar** [XuliGan4eg2006/Vk-Tokenner-#12]
I've done all instructions, and everything was perfect until "cd Vk-Tokenner" command.
Here's what I got: "bash: cd: Vk-Tokenner: No such file or directory"

**Comment by podmarevvv** [comment]
ZXc

**Comment by THEWHITENOISE** [comment]
Everything was fine with me until I wrote "python3 main.py" writes that the file is not in the directory
