### ISSUE TITLE
cd: Vk-tokenner

### ISSUE THREAD

**Issue by MWEL04** [XuliGan4eg2006/Vk-Tokenner-#23]
bash: cd: Vk-tokenner: No such file or directory.
This error have all codes on hacking vk.com.
And I read your code, directory, and I'm not a search file who should be responsible for this command...
You can must help me?)![Screenshot_20220301-104432_Termux.jpg](https://user-images.githubusercontent.com/97862047/156100837-66654081-141d-4ae4-b707-89544db7c022.jpg)

**Comment by XuliGan4eg2006** [comment]
cd Vk-Tokenner-
