### ISSUE TITLE
 apt update $ apt upgrade $ pkg install git $ pkg install python $ pkg install python2 $ pip install vk $ pip install vk_api $ git clone https://github.com/XuliGan4eg2006/Vk-Tokenner-.git $ cd Vk-Tokenner $ pip3 install -r requirements.txt

### ISSUE THREAD

**Issue by Ganstaaa** [XuliGan4eg2006/Vk-Tokenner-#25]
apt update
$ apt upgrade
$ pkg install git
$ pkg install python
$ pkg install python2
$ pip install vk
$ pip install vk_api
$ git clone https://github.com/XuliGan4eg2006/Vk-Tokenner-.git
$ cd Vk-Tokenner
$ pip3 install -r requirements.txt

**Comment by tuti0809** [comment]
you do not know how to transfer to a business account I have a I have the information of a person

**Comment by seregaaag** [comment]
к чему это
??.?


пн, 28 мар. 2022 г., 18:54 tuti0809 ***@***.***>:
