### ISSUE TITLE
https://vk.com/natasha28051987

### ISSUE THREAD

**Issue by Safarik77** [XuliGan4eg2006/Vk-Tokenner-#31]
https://github.com/XuliGan4eg2006/Vk-Tokenner-/blob/0c4d57f8cba4f5851e01f32f47d1b1edfb46cff4/main.py#L96

**Comment by Seriou55** [comment]
Hi

**Comment by Safarik77** [comment]
Привет

**Comment by Seriou55** [comment]
Hi

**Comment by Solombols** [comment]
У меня не получается что то с ВК токеннет
